### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by filmmakindan** [ProLoser/screenwriter#11]
Hey this is awesome!
wanted to play around with the code a bit for fun but didn't see a license file - what kind of license does this project have?
thanks!

**Comment by ProLoser** [comment]
Is GNU GPLv3 too restrictive for your purposes? I don't mind sharing the code and iterating on it, but I am not excited about it turning into a crappy celtx ripoff for money.

**Comment by ProLoser** [comment]
@filmmakindan @erikeah I went with MIT as the code will probably never be used in any other case.
\
